name: CI

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  test-chrome:
    name: Test on Chrome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Chrome tests
        run: npm run test:chrome

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chrome-test-results
          path: tests/browser-test-report.json
          if-no-files-found: ignore

  test-firefox:
    name: Test on Firefox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Firefox tests
        run: npm run test:firefox

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firefox-test-results
          path: tests/browser-test-report.json
          if-no-files-found: ignore

  test-edge:
    name: Test on Edge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Edge tests
        run: npm run test:edge

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: edge-test-results
          path: tests/browser-test-report.json
          if-no-files-found: ignore

  test-all-browsers:
    name: Cross-Browser Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run all browser tests
        run: npm run test:all-browsers

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-browsers-test-results
          path: tests/browser-test-report.json
          if-no-files-found: ignore

  validate:
    name: Full Validation
    runs-on: ubuntu-latest
    needs: [lint, test-chrome, test-firefox, test-edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run full validation
        run: npm run dev

      - name: Build extension
        run: npm run build
