name: Multi-Browser Test Matrix

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  test-matrix:
    name: Test ${{ matrix.browser }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chrome, firefox, edge]
        node-version: ['18', '20']
        exclude:
          # Edge is not available on macOS in CI
          - os: macos-latest
            browser: edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ${{ matrix.browser }} tests
        run: npm run test:${{ matrix.browser }}
        env:
          TEST_BROWSER: ${{ matrix.browser }}
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.browser }}-node${{ matrix.node-version }}
          path: tests/browser-test-report.json
          if-no-files-found: ignore

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: test-matrix
    if: always()

    steps:
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          path: test-results

      - name: Display test summary
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| OS | Browser | Node | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|---|---|" >> $GITHUB_STEP_SUMMARY

          for dir in test-results/*/; do
            if [ -f "$dir/browser-test-report.json" ]; then
              name=$(basename "$dir")
              echo "| $name | ✅ |" >> $GITHUB_STEP_SUMMARY
            fi
          done
